### ISSUE TITLE
shodown cli doesn't work with 2.0.0

### ISSUE THREAD

**Issue by gbtami** [showdownjs/showdown#893]
Maybe src/ is not in install?
```
tamas@tami:~$ /usr/bin/showdown -i
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../src/cli/cli'
Require stack:
- /usr/lib/node_modules/showdown/bin/showdown.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/showdown/bin/showdown.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/lib/node_modules/showdown/bin/showdown.js' ]
}
```

**Comment by tivie** [comment]
Seems the src directory is missing from the npm repository. @SyntaxRules

**Comment by tivie** [comment]
Found the culprit 35730b7c80a5574bcdf1e712e49d39987e7e4054

**Comment by gbtami** [comment]
After installing 2.0.1 I get this:
```
$ ./md2html.sh
/home/tamas/pychess-variants/node_modules/showdown/src/cli/makehtml.cmd.js:7
yargs.reset()
      ^

TypeError: yargs.reset is not a function
    at Object.<anonymous> (/home/tamas/pychess-variants/node_modules/showdown/src/cli/makehtml.cmd.js:7:7)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/tamas/pychess-variants/node_modules/showdown/src/cli/cli.js:37:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
/home/tamas/pychess-variants/node_modules/showdown/src/cli/makehtml.cmd.js:7
```

My script is here https://github.com/gbtami/pychess-variants/blob/master/md2html.sh

**Comment by tivie** [comment]
Hey there. Can you try the new version? Should be working now.

**Comment by gbtami** [comment]
1. I update showdown version to 2.0.2 in my project package.json
2. yarn install
I get this
```
tamas@tami:~/pychess-variants$ showdown -h
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../../dist/showdown'
Require stack:
- /home/tamas/pychess-variants/node_modules/showdown/bin/showdown.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/tamas/pychess-variants/node_modules/showdown/bin/showdown.js:2:3661)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/tamas/pychess-variants/node_modules/showdown/bin/showdown.js'
  ]
}
tamas@tami:~/pychess-variants$ ls -l node_modules/showdown/
összesen 36
drwxrwxr-x 2 tamas tamas  4096 márc   6 21:52 bin
drwxrwxr-x 2 tamas tamas  4096 márc   6 21:52 dist
-rw-r--r-- 1 tamas tamas  1072 okt   26  1985 LICENSE
-rw-r--r-- 1 tamas tamas  1622 okt   26  1985 package.json
-rw-r--r-- 1 tamas tamas 20212 okt   26  1985 README.md
tamas@tami:~/pychess-variants$ ls -l node_modules/showdown/dist/
összesen 764
-rw-r--r-- 1 tamas tamas 159755 okt   26  1985 showdown.js
-rw-r--r-- 1 tamas tamas 451629 okt   26  1985 showdown.js.map
-rw-r--r-- 1 tamas tamas  75209 okt   26  1985 showdown.min.js
-rw-r--r-- 1 tamas tamas  85554 okt   26  1985 showdown.min.js.map
tamas@tami:~/pychess-variants$ 
```

**Comment by gbtami** [comment]
Maybe I'm doing something wrong. But this worked with 1.9.1

**Comment by tivie** [comment]
is showdown installed globally or locally? I've just tested a fresh install and it's working in my dev environment

**Comment by gbtami** [comment]
I think "yarn install" works locally.

**Comment by tivie** [comment]
seems there's some path issues with yarn.

Can you replace the contents of `node_modules/showdown/bin/showdown.js` with the contents of this file? https://github.com/showdownjs/showdown/blob/version_2.x/src/cli/cli.js

Just copy and paste [this](https://github.com/showdownjs/showdown/blob/version_2.x/src/cli/cli.js) into `node_modules/showdown/bin/showdown.js` and test if the cli now works.

**Comment by gbtami** [comment]
First of all thank you very much helping to solve this issue!
Unfortunately I'm ill with fever now, so possible can continue it next week only.

**Comment by tivie** [comment]
no problem. I hope you get better soon.
