### ISSUE TITLE
CLI not working with jsdom v10

### ISSUE THREAD

**Issue by PotOfCoffee2Go** [showdownjs/showdown#554]
Freshly installed showdown `npm install -g`

`showdown makehtml -i intro.md -o intro.html` gets : 

```
/home/kim/Desktop/projects/node/showdown/dist/showdown.js:585
  this.window = require('jsdom').jsdom('', {}).defaultView; // jshint ignore:line
                                 ^

TypeError: require(...).jsdom is not a function
    at Object.<anonymous> (/home/kim/Desktop/projects/node/showdown/dist/showdown.js:585:34)
    at Object.<anonymous> (/home/kim/Desktop/projects/node/showdown/dist/showdown.js:5090:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/kim/Desktop/projects/node/showdown/src/cli/makehtml.cmd.js:4:16)

```
When I change package.json `"jsdom": "^10.0.0",` to `"jsdom": "^9.12.0",`. - reinstall- and works ok. 

So assume something to do when upgraded showdown from jsdom v9 to v10.

**Comment by tivie** [comment]
thank you
I will look into it
